version: '2'
services:
  intellij:
    image: psharkey/intellij:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: psharkey/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    ports:
      - "8080:8080"
    networks:
      - x11

  ide:
    image: kdelfour/cloud9-docker
    volumes:
      - ./:/workspace:z
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:80

  grok:
    image: scue/docker-opengrok
    volumes:
      - ./.opengrok:/src
    ports:
      - 8082:8080

networks:
  x11:
